version: '3.9'

services:
  confluence:
    build: .
    image: example.com/confluence:8.0.3
    container_name: confluence
    restart: unless-stopped
    environment:
      - TZ=Asia/Tehran
    ports:
      - 8080:8090
    volumes:
      - data:/var/atlassian/application-data/confluence
  
  postgres:
    image: postgres:15.1
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=PASSWORD
      - POSTGRES_DB=confluence
    ports:
      - 5432:5432
    volumes:
      - pgsql:/var/lib/postgresql/data

volumes:
  data:
  pgsql:
